# Site settings
title: Robbie's Test Jekyll Site
baseurl: "/JekyllTest" # the subpath of your site, e.g. /blog/
url: "https://robbies.club" # the base hostname & protocol for your site

# Build settings
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
permalink: /:title/
